/// Banque de questions du Quiz Karataka. `a` = bonne réponse, `w` = trois
/// mauvaises réponses ; l'ordre des choix est mélangé à chaque partie.
export interface QuizQuestion {
  c: 'Madagascar' | 'Afrique' | 'Monde' | 'Sciences' | 'Sport' | 'Culture';
  q: string;
  a: string;
  w: [string, string, string];
}

export const QUIZ_QUESTIONS: QuizQuestion[] = [
  // Madagascar
  { c: 'Madagascar', q: 'Quelle est la capitale de Madagascar ?', a: 'Antananarivo', w: ['Toamasina', 'Mahajanga', 'Fianarantsoa'] },
  { c: 'Madagascar', q: 'Quelle est la monnaie de Madagascar ?', a: "L'ariary", w: ['Le franc malgache', 'La roupie', 'Le shilling'] },
  { c: 'Madagascar', q: "En quelle année Madagascar a-t-il obtenu son indépendance ?", a: '1960', w: ['1958', '1972', '1947'] },
  { c: 'Madagascar', q: "Quel jour est célébrée la fête de l'indépendance ?", a: '26 juin', w: ['14 juillet', '29 mars', '1er mai'] },
  { c: 'Madagascar', q: 'Quel est le plus haut sommet de Madagascar ?', a: 'Le Maromokotro', w: ["L'Ankaratra", "L'Andringitra", 'Le Tsiafajavona'] },
  { c: 'Madagascar', q: 'Dans quel océan se trouve Madagascar ?', a: "L'océan Indien", w: ["L'océan Atlantique", "L'océan Pacifique", "L'océan Arctique"] },
  { c: 'Madagascar', q: "Quel bras de mer sépare Madagascar de l'Afrique ?", a: 'Le canal du Mozambique', w: ['Le golfe d’Aden', 'La mer Rouge', 'Le détroit de Gibraltar'] },
  { c: 'Madagascar', q: 'Madagascar est la … plus grande île du monde.', a: '4e', w: ['2e', '7e', '10e'] },
  { c: 'Madagascar', q: 'Quel animal endémique est le symbole de la faune malgache ?', a: 'Le lémurien', w: ['Le zèbre', 'Le koala', 'Le panda'] },
  { c: 'Madagascar', q: "Près de quelle ville se trouve la célèbre allée des Baobabs ?", a: 'Morondava', w: ['Antsirabe', 'Toliara', 'Antsiranana'] },
  { c: 'Madagascar', q: 'Quel est le principal port de Madagascar ?', a: 'Toamasina', w: ['Mahajanga', 'Toliara', 'Morondava'] },
  { c: 'Madagascar', q: 'Le Fanorona est…', a: 'Un jeu de plateau traditionnel malgache', w: ['Une danse du Sud', 'Un plat à base de riz', 'Un instrument de musique'] },
  { c: 'Madagascar', q: 'La valiha est…', a: 'Un instrument de musique en bambou', w: ['Un plat traditionnel', 'Un jeu de cartes', 'Une fête religieuse'] },
  { c: 'Madagascar', q: 'Le ravitoto est préparé à base de…', a: 'Feuilles de manioc pilées', w: ['Poisson séché', 'Riz rouge', 'Haricots blancs'] },
  { c: 'Madagascar', q: 'Quel est l’aliment de base des Malgaches ?', a: 'Le riz', w: ['Le maïs', 'Le blé', 'La pomme de terre'] },
  { c: 'Madagascar', q: 'Le famadihana est…', a: 'Le retournement des morts', w: ['Une course de pirogues', 'Une fête des récoltes', 'Un mariage royal'] },
  { c: 'Madagascar', q: 'Le hira gasy est…', a: 'Un spectacle traditionnel de chants, danses et discours', w: ['Un sport de combat', 'Un marché hebdomadaire', 'Un dessert'] },
  { c: 'Madagascar', q: 'Qui fut le premier président de la République malgache ?', a: 'Philibert Tsiranana', w: ['Didier Ratsiraka', 'Albert Zafy', 'Marc Ravalomanana'] },
  { c: 'Madagascar', q: 'Quel est le surnom de l’équipe nationale de football ?', a: 'Les Barea', w: ['Les Makis', 'Les Lions', 'Les Éléphants'] },
  { c: 'Madagascar', q: 'Quel est le surnom de l’équipe nationale de rugby ?', a: 'Les Makis', w: ['Les Barea', 'Les Fossas', 'Les Zébus'] },
  { c: 'Madagascar', q: 'En quelle année Madagascar a-t-il disputé sa première CAN de football ?', a: '2019', w: ['2004', '2012', '1998'] },
  { c: 'Madagascar', q: 'Quelle île du nord-ouest est surnommée « l’île aux parfums » ?', a: 'Nosy Be', w: ['Sainte-Marie', 'Nosy Komba', 'Mayotte'] },
  { c: 'Madagascar', q: 'Le fossa est…', a: 'Un carnivore endémique de Madagascar', w: ['Un oiseau migrateur', 'Un poisson de lac', 'Un arbre géant'] },
  { c: 'Madagascar', q: 'De quelle épice Madagascar est-il le premier producteur mondial ?', a: 'La vanille', w: ['Le poivre', 'La cannelle', 'Le safran'] },
  { c: 'Madagascar', q: 'Quel roi a unifié le royaume merina à la fin du XVIIIe siècle ?', a: 'Andrianampoinimerina', w: ['Radama II', 'Andriamasinavalona', 'Ralambo'] },
  { c: 'Madagascar', q: 'Dans quelle ville se trouve le Rova, palais de la Reine ?', a: 'Antananarivo', w: ['Fianarantsoa', 'Ambositra', 'Antsirabe'] },
  { c: 'Madagascar', q: 'Quel est le plus grand lac de Madagascar ?', a: 'Le lac Alaotra', w: ['Le lac Itasy', 'Le lac Tritriva', 'Le lac Kinkony'] },
  { c: 'Madagascar', q: 'Les Tsingy de Bemaraha sont célèbres pour…', a: 'Leurs aiguilles de calcaire', w: ['Leurs volcans actifs', 'Leurs glaciers', 'Leurs dunes de sable'] },
  { c: 'Madagascar', q: 'Comment commence l’hymne national malgache ?', a: 'Ry Tanindrazanay malala ô', w: ['Ny fitiavana', 'Ry tanindrazana', 'Isika mianakavy'] },
  { c: 'Madagascar', q: 'Ambohimanga, inscrite au patrimoine mondial de l’UNESCO, est…', a: 'Une colline royale', w: ['Une forêt de baobabs', 'Une plage du Sud', 'Un parc marin'] },
  { c: 'Madagascar', q: 'Le salegy est…', a: 'Un style musical de Madagascar', w: ['Un plat de zébu', 'Une pirogue', 'Un jeu de dés'] },
  { c: 'Madagascar', q: 'Quel animal est très utilisé pour les travaux des champs à Madagascar ?', a: 'Le zébu', w: ['Le chameau', 'Le cheval', "L'âne"] },

  // Afrique
  { c: 'Afrique', q: 'Quel est le plus long fleuve d’Afrique ?', a: 'Le Nil', w: ['Le Congo', 'Le Niger', 'Le Zambèze'] },
  { c: 'Afrique', q: 'Quel est le plus haut sommet d’Afrique ?', a: 'Le Kilimandjaro', w: ['Le mont Kenya', 'Le mont Cameroun', 'Le Ras Dashen'] },
  { c: 'Afrique', q: 'Quel est le plus grand désert chaud du monde ?', a: 'Le Sahara', w: ['Le Kalahari', 'Le Namib', 'Le désert de Gobi'] },
  { c: 'Afrique', q: 'Quelle est la capitale du Kenya ?', a: 'Nairobi', w: ['Mombasa', 'Kampala', 'Addis-Abeba'] },
  { c: 'Afrique', q: 'Quelle est la capitale du Maroc ?', a: 'Rabat', w: ['Casablanca', 'Marrakech', 'Fès'] },
  { c: 'Afrique', q: 'Quelle est la capitale du Nigeria ?', a: 'Abuja', w: ['Lagos', 'Ibadan', 'Kano'] },
  { c: 'Afrique', q: 'Quelle est la capitale du Sénégal ?', a: 'Dakar', w: ['Saint-Louis', 'Bamako', 'Conakry'] },
  { c: 'Afrique', q: 'Quelle est la capitale de l’île Maurice ?', a: 'Port-Louis', w: ['Curepipe', 'Mahébourg', 'Victoria'] },
  { c: 'Afrique', q: 'Quelle est la capitale des Comores ?', a: 'Moroni', w: ['Mutsamudu', 'Mamoudzou', 'Fomboni'] },
  { c: 'Afrique', q: 'Quelle est la capitale des Seychelles ?', a: 'Victoria', w: ['Port-Louis', 'Moroni', 'Mahé'] },
  { c: 'Afrique', q: 'Quelle est la capitale du Mozambique ?', a: 'Maputo', w: ['Beira', 'Nampula', 'Lusaka'] },
  { c: 'Afrique', q: 'Quelle est la capitale de l’Égypte ?', a: 'Le Caire', w: ['Alexandrie', 'Louxor', 'Assouan'] },
  { c: 'Afrique', q: 'Quel est le pays le plus peuplé d’Afrique ?', a: 'Le Nigeria', w: ['L’Égypte', 'L’Éthiopie', 'L’Afrique du Sud'] },
  { c: 'Afrique', q: 'Dans quel pays se trouvent les pyramides de Gizeh ?', a: 'L’Égypte', w: ['Le Soudan', 'La Libye', 'Le Maroc'] },
  { c: 'Afrique', q: 'De quel pays Nelson Mandela a-t-il été président ?', a: "L'Afrique du Sud", w: ['Le Zimbabwe', 'La Namibie', 'Le Botswana'] },
  { c: 'Afrique', q: 'Quel est le chef-lieu de La Réunion ?', a: 'Saint-Denis', w: ['Saint-Pierre', 'Saint-Paul', 'Le Port'] },

  // Monde
  { c: 'Monde', q: 'Quel est le plus grand océan du monde ?', a: "L'océan Pacifique", w: ["L'océan Atlantique", "L'océan Indien", "L'océan Arctique"] },
  { c: 'Monde', q: 'Quel est le plus haut sommet du monde ?', a: "L'Everest", w: ['Le K2', 'Le mont Blanc', "L'Aconcagua"] },
  { c: 'Monde', q: 'Quel est le plus grand pays du monde par la superficie ?', a: 'La Russie', w: ['Le Canada', 'La Chine', 'Les États-Unis'] },
  { c: 'Monde', q: 'Quel est le pays le plus peuplé du monde ?', a: "L'Inde", w: ['La Chine', 'Les États-Unis', "L'Indonésie"] },
  { c: 'Monde', q: 'Quelle est la capitale du Japon ?', a: 'Tokyo', w: ['Osaka', 'Kyoto', 'Séoul'] },
  { c: 'Monde', q: 'Quelle est la capitale du Canada ?', a: 'Ottawa', w: ['Toronto', 'Montréal', 'Vancouver'] },
  { c: 'Monde', q: "Quelle est la capitale de l'Australie ?", a: 'Canberra', w: ['Sydney', 'Melbourne', 'Perth'] },
  { c: 'Monde', q: 'Quelle est la capitale du Brésil ?', a: 'Brasília', w: ['Rio de Janeiro', 'São Paulo', 'Salvador'] },
  { c: 'Monde', q: 'Quelle est la capitale de la Turquie ?', a: 'Ankara', w: ['Istanbul', 'Izmir', 'Antalya'] },
  { c: 'Monde', q: 'Quelle est la capitale de la Corée du Sud ?', a: 'Séoul', w: ['Busan', 'Pyongyang', 'Tokyo'] },
  { c: 'Monde', q: "Quelle est la capitale de l'Argentine ?", a: 'Buenos Aires', w: ['Santiago', 'Montevideo', 'Lima'] },
  { c: 'Monde', q: "Quelle est la capitale de l'Inde ?", a: 'New Delhi', w: ['Mumbai', 'Calcutta', 'Bangalore'] },
  { c: 'Monde', q: 'Quelle est la monnaie du Japon ?', a: 'Le yen', w: ['Le yuan', 'Le won', 'Le dollar'] },
  { c: 'Monde', q: 'Quelle est la monnaie du Royaume-Uni ?', a: 'La livre sterling', w: ["L'euro", 'Le dollar', 'Le franc'] },
  { c: 'Monde', q: 'Dans quelle ville se trouve la tour Eiffel ?', a: 'Paris', w: ['Lyon', 'Bruxelles', 'Marseille'] },
  { c: 'Monde', q: 'En quelle année l’homme a-t-il marché sur la Lune pour la première fois ?', a: '1969', w: ['1959', '1975', '1981'] },
  { c: 'Monde', q: 'Qui a été le premier homme à marcher sur la Lune ?', a: 'Neil Armstrong', w: ['Youri Gagarine', 'Buzz Aldrin', 'Thomas Pesquet'] },
  { c: 'Monde', q: 'En quelle année est tombé le mur de Berlin ?', a: '1989', w: ['1991', '1979', '1985'] },

  // Sciences
  { c: 'Sciences', q: 'Quelle planète est la plus proche du Soleil ?', a: 'Mercure', w: ['Vénus', 'Mars', 'La Terre'] },
  { c: 'Sciences', q: 'Quelle est la plus grande planète du système solaire ?', a: 'Jupiter', w: ['Saturne', 'Neptune', 'La Terre'] },
  { c: 'Sciences', q: 'Quelle planète est surnommée « la planète rouge » ?', a: 'Mars', w: ['Vénus', 'Jupiter', 'Mercure'] },
  { c: 'Sciences', q: 'Quelle est la formule chimique de l’eau ?', a: 'H2O', w: ['CO2', 'O2', 'NaCl'] },
  { c: 'Sciences', q: "Quel est le symbole chimique de l'or ?", a: 'Au', w: ['Ag', 'Or', 'Fe'] },
  { c: 'Sciences', q: 'Combien d’os compte le squelette d’un adulte ?', a: '206', w: ['186', '250', '312'] },
  { c: 'Sciences', q: 'Combien de chromosomes possède une cellule humaine normale ?', a: '46', w: ['23', '44', '48'] },
  { c: 'Sciences', q: 'Quel gaz les plantes absorbent-elles pour la photosynthèse ?', a: 'Le dioxyde de carbone', w: ["L'oxygène", "L'azote", "L'hélium"] },
  { c: 'Sciences', q: "À quelle température l'eau bout-elle au niveau de la mer ?", a: '100 °C', w: ['90 °C', '80 °C', '120 °C'] },
  { c: 'Sciences', q: 'Qui a formulé la théorie de la relativité ?', a: 'Albert Einstein', w: ['Isaac Newton', 'Marie Curie', 'Galilée'] },
  { c: 'Sciences', q: 'Quel est le plus grand mammifère du monde ?', a: 'La baleine bleue', w: ["L'éléphant d'Afrique", 'Le requin-baleine', 'La girafe'] },
  { c: 'Sciences', q: 'Quel est l’animal terrestre le plus rapide ?', a: 'Le guépard', w: ['Le lion', "L'antilope", 'Le cheval'] },
  { c: 'Sciences', q: 'Quel organe pompe le sang dans le corps ?', a: 'Le cœur', w: ['Le foie', 'Les poumons', 'Les reins'] },
  { c: 'Sciences', q: 'Combien de minutes y a-t-il dans une journée ?', a: '1 440', w: ['1 200', '2 400', '960'] },
  { c: 'Sciences', q: 'Combien de côtés a un hexagone ?', a: '6', w: ['5', '7', '8'] },
  { c: 'Sciences', q: 'Combien font 7 × 8 ?', a: '56', w: ['54', '48', '64'] },
  { c: 'Sciences', q: 'Quelle est la racine carrée de 144 ?', a: '12', w: ['14', '11', '16'] },
  { c: 'Sciences', q: 'Combien font 15 % de 200 ?', a: '30', w: ['15', '20', '40'] },
  { c: 'Sciences', q: 'Quelle est la vitesse approximative de la lumière ?', a: '300 000 km/s', w: ['30 000 km/s', '3 000 km/s', '3 millions de km/s'] },

  // Sport
  { c: 'Sport', q: 'Quel pays a gagné la Coupe du monde de football 2022 ?', a: "L'Argentine", w: ['La France', 'Le Brésil', 'Le Maroc'] },
  { c: 'Sport', q: 'Quel pays a gagné la Coupe du monde de football 2018 ?', a: 'La France', w: ['La Croatie', "L'Allemagne", 'La Belgique'] },
  { c: 'Sport', q: 'Quel pays a gagné la CAN 2023 (jouée en 2024) ?', a: "La Côte d'Ivoire", w: ['Le Nigeria', 'Le Sénégal', "L'Égypte"] },
  { c: 'Sport', q: 'Combien de joueurs une équipe de football aligne-t-elle sur le terrain ?', a: '11', w: ['10', '12', '9'] },
  { c: 'Sport', q: 'Combien de joueurs compte une équipe de rugby à XV sur le terrain ?', a: '15', w: ['13', '11', '12'] },
  { c: 'Sport', q: 'Combien de joueurs une équipe de basket aligne-t-elle sur le terrain ?', a: '5', w: ['6', '7', '4'] },
  { c: 'Sport', q: 'Quelle ville a accueilli les Jeux olympiques d’été 2024 ?', a: 'Paris', w: ['Tokyo', 'Los Angeles', 'Londres'] },
  { c: 'Sport', q: 'Quelle ville accueillera les Jeux olympiques d’été 2028 ?', a: 'Los Angeles', w: ['Brisbane', 'Paris', 'Madrid'] },
  { c: 'Sport', q: 'De quel pays est originaire le sprinteur Usain Bolt ?', a: 'La Jamaïque', w: ['Les États-Unis', 'Le Kenya', 'Trinité-et-Tobago'] },
  { c: 'Sport', q: 'Quel tournoi de tennis se joue sur terre battue à Paris ?', a: 'Roland-Garros', w: ['Wimbledon', "L'US Open", "L'Open d'Australie"] },
  { c: 'Sport', q: "Aux échecs, quelle pièce se déplace en « L » ?", a: 'Le cavalier', w: ['Le fou', 'La tour', 'La dame'] },
  { c: 'Sport', q: 'Combien de cases compte un échiquier ?', a: '64', w: ['81', '100', '49'] },

  // Culture
  { c: 'Culture', q: 'Qui a peint la Joconde ?', a: 'Léonard de Vinci', w: ['Michel-Ange', 'Picasso', 'Van Gogh'] },
  { c: 'Culture', q: 'Qui a écrit « Les Misérables » ?', a: 'Victor Hugo', w: ['Émile Zola', 'Alexandre Dumas', 'Molière'] },
  { c: 'Culture', q: 'Qui a écrit « Roméo et Juliette » ?', a: 'William Shakespeare', w: ['Charles Dickens', 'Molière', 'Victor Hugo'] },
  { c: 'Culture', q: 'Quel instrument possède généralement 88 touches ?', a: 'Le piano', w: ["L'accordéon", "L'orgue de barbarie", 'Le xylophone'] },
  { c: 'Culture', q: 'Qui a cofondé Microsoft ?', a: 'Bill Gates', w: ['Steve Jobs', 'Mark Zuckerberg', 'Elon Musk'] },
  { c: 'Culture', q: 'Qui a cofondé Apple ?', a: 'Steve Jobs', w: ['Bill Gates', 'Jeff Bezos', 'Larry Page'] },
  { c: 'Culture', q: 'Qui a créé Facebook ?', a: 'Mark Zuckerberg', w: ['Jack Dorsey', 'Elon Musk', 'Bill Gates'] },
  { c: 'Culture', q: 'Que signifie « WWW » ?', a: 'World Wide Web', w: ['World Web Wire', 'Wide World Window', 'Web World Wide'] },
  { c: 'Culture', q: 'Quel langage sert à structurer les pages web ?', a: 'HTML', w: ['PDF', 'MP3', 'JPEG'] },
  { c: 'Culture', q: 'Quelle entreprise a créé TikTok ?', a: 'ByteDance', w: ['Meta', 'Google', 'Tencent'] },
];
